### ISSUE TITLE
Discrépancie entre Panama et Auschiwtz

### ISSUE THREAD

**Issue by Cgg** [feston/bizkit#3]
Le mode de calcul des gorgées entre Panama et Auschwitz est différent. Dans un cas il faut relancer un dé, dans l'autre on se contente de regarder la valeur de l'autre dé qui vient d'être lancé. Du coup ça n'est pas vraiment « idem » comme le dit la règle.

Personnellement je préfère regarder la valeur de l'autre dé, le jeu va plus vite et d'un point de vue des probabilités ça revient exactement au même.

J'en appelle aux experts, @rlustin @basilesimon

**Comment by basilesimon** [comment]
Bien vu, Charlie Golf, je fixe dans ton sens - le côté fun du lancer de dé supplémentaire est en fait une perte de performance notable qui introduit pas mal de latence.

**Comment by Cgg** [comment]
:+1:
